name: Android CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]  # 当创建 release 时触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease  # 生成 release APK
    - name: Upload APK to Release
      uses: softprops/action-gh-release@v1
      with:
        tag: ${{ github.event.release.tag }}  # 使用发布的标签
        files: app/build/outputs/apk/release/app-release.apk  # APK 文件路径
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token