name: Build and Release APK

on:
  release:
    types: [created] # 当创建 Release 时触发

permissions:
  contents: write # 允许修改 Release 内容

jobs:
  build-and-upload-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: temurin
        cache: gradle

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > my-release-key.jks

    - name: Sign APK
      run: |
        $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
          --ks my-release-key.jks \
          --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
          --key-pass pass:${{ secrets.KEY_PASSWORD }} \
          --out app-release-vgal.apk \  # 输出文件名带有 vgal 后缀
          app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Verify signed APK
      run: |
        $ANDROID_HOME/build-tools/34.0.0/apksigner verify app-release-vgal.apk

    - name: Upload APK to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: app-release-vgal.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
