name: Build and Upload APK

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: temurin
        cache: gradle

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Generate a signing key
      run: |
        keytool -genkeypair -v \
          -keystore temp-key.jks \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -alias temp-key \
          -storepass temp-pass \
          -keypass temp-pass \
          -dname "CN=Temporary, OU=Temporary, O=Temporary, L=Temporary, S=Temporary, C=US"

    - name: Sign APK
      run: |
        $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
          --ks temp-key.jks \
          --ks-pass pass:temp-pass \
          --key-pass pass:temp-pass \
          --out app-release-signed.apk \
          app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Verify signed APK
      run: |
        $ANDROID_HOME/build-tools/34.0.0/apksigner verify app-release-signed.apk

    - name: Upload Signed APK to Release
      uses: softprops/action-gh-release@v1
      with:
        files: app-release-signed.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
