name: Android CI

on:
  release:
    types: [created]  # 仅在创建 release 时触发

permissions:
  contents: write  # 确保拥有写权限上传到 Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - uses: actions/checkout@v4

    # 2. 设置 JDK 环境
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # 3. 设置权限
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 4. 编译 Release APK
    - name: Build Release APK
      run: ./gradlew assembleRelease

    # 5. 验证 APK 是否生成
    - name: Verify APK File
      run: ls -la app/build/outputs/apk/release/

    # 6. 上传 APK 到 Release
    - name: Upload APK to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.release.tag_name }}  # 从 release 事件获取标签
        files: app/build/outputs/apk/release/app-release.apk  # 工作流动态生成的 APK 文件
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
